//file generated by bootstrap.cpp, do not edit.

#ifndef PRIVATE_KEY_H_
#define PRIVATE_KEY_H_
#define PRIVATE_KEY { \
"-----BEGIN RSA PRIVATE KEY-----\n" \
"MIICXQIBAAKBgQC/1JPkR1vvwa+RYOGlYnBrRvTjd+3cluxTKcsNH1Xl35fC+5ii\n" \
"2DQujOi1nuTHAsCkDkoKIvGUDFgX+DKVHOUzzhBm9YHXgvko1Ve3lMuztIKONgwF\n" \
"B1IOWjvjyxe3DYRNwIuPX5qDKUwebofW7hZxnFPF7xXYXr6ZPls887kDywIDAQAB\n" \
"AoGARMArQOVSTdtc0P2n4V4mbExB+ERDO4vbpvKTk2BnqLs56OfDDJnwGb7mqDEK\n" \
"TUjvQdzdLETZz/WcnPqXJln0yrw3vrOKBZSmaXOuETZXGcGBpRpmN5i6Yy6MTg0e\n" \
"gsjirfCtBDpt9PmfjNSQby6T0pkUcItT+cPzo8DfhdalvAECQQD7LX7Kj5BOvQ/o\n" \
"PKvY+1HGVi3Qhl6rNVrcwHQPMEs16KQoDztxyF/73a/QCmPOXkf4jcMYE6ZIMGHJ\n" \
"tnrM8z1zAkEAw4Nl8768DskFztrRcLys/1A6bF/JP6pZD3MaWygerr3xO2sClWID\n" \
"Wz7ts8uIwjcagHh6eMpWGYxjhr5+mLIKSQJBALb86Q8nUgmbATi+4q9cQLIO3Ke7\n" \
"DMMMRtrmNmdOVqy6hMVOe48kXJEAa3JT72xMEYDJvmUPA6g53zP2BjbDynMCQAkl\n" \
"io1+rNmcOfNVdVrq2MURAcq0KHwcAhKg9eix1c2jATggZ3yJm1KXfRNeQEWlwk2k\n" \
"VUZ1YNXNJZLWMqH+IlECQQDLQqNb6OBu8wySfeZWR1Q0Yt+HKR0cBeUNDWjGTPDB\n" \
"a6bezsj/4cHD/PNK2eHm73W3WVA5ozWMOQaEPyEYjERp\n" \
"-----END RSA PRIVATE KEY-----\n" \
""}

#endif
