//file generated by bootstrap.cpp, do not edit.

#ifndef PUBLIC_KEY_H_
#define PUBLIC_KEY_H_
#define PUBLIC_KEY { \
"-----BEGIN RSA PUBLIC KEY-----\n" \
"MIGJAoGBAL/Uk+RHW+/Br5Fg4aVicGtG9ON37dyW7FMpyw0fVeXfl8L7mKLYNC6M\n" \
"6LWe5McCwKQOSgoi8ZQMWBf4MpUc5TPOEGb1gdeC+SjVV7eUy7O0go42DAUHUg5a\n" \
"O+PLF7cNhE3Ai49fmoMpTB5uh9buFnGcU8XvFdhevpk+WzzzuQPLAgMBAAE=\n" \
"-----END RSA PUBLIC KEY-----\n" \
""}

#define SHARED_RANDOM 383;
#endif
